"""Defence-research abstractions of publicly discussed phishing patterns.

Only structural characteristics are stored: topic, information order, sentence
bands, urgency, authority, evidence style, personalisation, CTA placement,
layout, density, timing relation, requested action, and the signals a defender
should check. No company name, logo, URL, address, or original sentence from
any real campaign is stored here or produced from here.
"""

from __future__ import annotations

from typing import Any


PATTERN_LIBRARY: dict[str, dict[str, Any]] = {
    "account_security_alert": {
        "subject_theme": "unfamiliar_signin_review",
        "opening_style": "observed_activity",
        "evidence_style": "device_summary",
        "consequence_style": "none",
        "reassurance_style": "support_contact",
        "urgency_level": "medium",
        "authority_level": "medium",
        "sentence_count_band": "medium",
        "semantic_sequence_variant": "standard",
        "personalization_level": "named_recipient",
        "CTA_position": "below_body",
        "template_family": "alert_polished",
        "information_density": "medium",
        "timing_variant": "with_official",
        "desired_user_action": "click",
        "defender_signals": ("sender_auth", "destination_ownership"),
    },
    "account_enforcement": {
        "subject_theme": "policy_violation_notice",
        "opening_style": "policy_reference",
        "evidence_style": "unbacked_assertion",
        "consequence_style": "access_restriction",
        "reassurance_style": "none",
        "urgency_level": "high",
        "authority_level": "high",
        "sentence_count_band": "medium",
        "semantic_sequence_variant": "cta_early",
        "personalization_level": "generic",
        "CTA_position": "above_body",
        "template_family": "alert_basic",
        "information_density": "short",
        "timing_variant": "before_official",
        "desired_user_action": "submit",
        "defender_signals": ("signature_validity", "official_event_record"),
    },
    "policy_violation_notice": {
        "subject_theme": "policy_violation_notice",
        "opening_style": "policy_reference",
        "evidence_style": "referenced_record",
        "consequence_style": "review_deadline",
        "reassurance_style": "safety_note",
        "urgency_level": "medium",
        "authority_level": "high",
        "sentence_count_band": "long",
        "semantic_sequence_variant": "evidence_first",
        "personalization_level": "named_recipient",
        "CTA_position": "below_body",
        "template_family": "alert_polished",
        "information_density": "long",
        "timing_variant": "after_official",
        "desired_user_action": "click",
        "defender_signals": ("official_event_record", "state_consistency"),
    },
    "device_login_warning": {
        "subject_theme": "device_login_warning",
        "opening_style": "observed_activity",
        "evidence_style": "device_summary",
        "consequence_style": "access_restriction",
        "reassurance_style": "support_contact",
        "urgency_level": "high",
        "authority_level": "medium",
        "sentence_count_band": "short",
        "semantic_sequence_variant": "standard",
        "personalization_level": "named_recipient",
        "CTA_position": "below_body",
        "template_family": "alert_basic",
        "information_density": "short",
        "timing_variant": "with_official",
        "desired_user_action": "click",
        "defender_signals": ("sender_auth", "display_alignment"),
    },
    "recovery_followup": {
        "subject_theme": "recovery_followup",
        "opening_style": "support_greeting",
        "evidence_style": "referenced_record",
        "consequence_style": "none",
        "reassurance_style": "support_contact",
        "urgency_level": "low",
        "authority_level": "medium",
        "sentence_count_band": "medium",
        "semantic_sequence_variant": "standard",
        "personalization_level": "named_recipient",
        "CTA_position": "below_instruction",
        "template_family": "alert_polished",
        "information_density": "medium",
        "timing_variant": "after_official",
        "desired_user_action": "submit",
        "defender_signals": ("destination_ownership", "signature_validity"),
    },
    "support_impersonation": {
        "subject_theme": "account_security_notice",
        "opening_style": "support_greeting",
        "evidence_style": "unbacked_assertion",
        "consequence_style": "none",
        "reassurance_style": "support_contact",
        "urgency_level": "low",
        "authority_level": "high",
        "sentence_count_band": "medium",
        "semantic_sequence_variant": "standard",
        "personalization_level": "named_recipient",
        "CTA_position": "below_body",
        "template_family": "alert_polished",
        "information_density": "medium",
        "timing_variant": "before_official",
        "desired_user_action": "click",
        "defender_signals": ("sender_registry", "display_alignment"),
    },
    "event_shadowing": {
        "subject_theme": "unfamiliar_signin_review",
        "opening_style": "observed_activity",
        "evidence_style": "referenced_record",
        "consequence_style": "access_restriction",
        "reassurance_style": "safety_note",
        "urgency_level": "high",
        "authority_level": "high",
        "sentence_count_band": "medium",
        "semantic_sequence_variant": "evidence_first",
        "personalization_level": "named_recipient",
        "CTA_position": "below_body",
        "template_family": "alert_incident_echo",
        "information_density": "medium",
        "timing_variant": "after_official",
        "desired_user_action": "submit",
        "defender_signals": ("sender_auth", "signature_validity",
                             "destination_ownership"),
    },
    "warning_escape_test": {
        "subject_theme": "account_security_notice",
        "opening_style": "observed_activity",
        "evidence_style": "device_summary",
        "consequence_style": "review_deadline",
        "reassurance_style": "safety_note",
        "urgency_level": "high",
        "authority_level": "medium",
        "sentence_count_band": "short",
        "semantic_sequence_variant": "cta_early",
        "personalization_level": "named_recipient",
        "CTA_position": "above_body",
        "template_family": "alert_polished",
        "information_density": "short",
        "timing_variant": "with_official",
        "desired_user_action": "ignore_warning",
        "defender_signals": ("destination_ownership",),
    },
    "visual_trust_abuse": {
        "subject_theme": "unfamiliar_signin_review",
        "opening_style": "observed_activity",
        "evidence_style": "referenced_record",
        "consequence_style": "none",
        "reassurance_style": "support_contact",
        "urgency_level": "low",
        "authority_level": "medium",
        "sentence_count_band": "medium",
        "semantic_sequence_variant": "standard",
        "personalization_level": "named_recipient",
        "CTA_position": "below_body",
        "template_family": "alert_polished",
        "information_density": "medium",
        "timing_variant": "with_official",
        "desired_user_action": "submit",
        "defender_signals": ("official_event_record", "sender_auth"),
    },
    "synthetic_copyright_claim": {
        "subject_theme": "policy_violation_notice",
        "opening_style": "policy_reference",
        "evidence_style": "referenced_record",
        "consequence_style": "review_deadline",
        "reassurance_style": "none",
        "urgency_level": "medium",
        "authority_level": "high",
        "sentence_count_band": "long",
        "semantic_sequence_variant": "evidence_first",
        "personalization_level": "generic",
        "CTA_position": "below_body",
        "template_family": "alert_basic",
        "information_density": "long",
        "timing_variant": "before_official",
        "desired_user_action": "click",
        "defender_signals": ("official_event_record", "sender_registry"),
    },
}

PATTERN_NAMES: tuple[str, ...] = tuple(PATTERN_LIBRARY)
