[theme]
primaryColor = "#14B8A6"
backgroundColor = "#07111F"
secondaryBackgroundColor = "#111E31"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
